### ISSUE TITLE
How to create  SDL_PIXELFORMAT_NV12 texture

### ISSUE THREAD

**Issue by 289523052** [ppy/SDL2-CS#134]
I want to use SDL_UpdateNVTexture, but cannot be created SDL_PIXELFORMAT_NV12 texture

**Comment by smoogipoo** [comment]
It will need to be PR to / added to https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs first.

**Comment by 289523052** [comment]
I added SDL_ PIXELFORMAT_ Nv12, but the display is incorrect.I use ffmpeg. av_ hwframe_ transfer_ Data hard decoding to obtain nv12, I don't know if it can't be used directly
