### ISSUE TITLE
Issue with osx-x64 native

### ISSUE THREAD

**Issue by elvodqa** [ppy/SDL2-CS#143]
Just updated the Nuget package to the latest. I've had no issues with Windows but trying to run my project on MacOS, I've got an error saying `Window data not set` when trying to load textures. Program was using package's native so removing the osx-x64 native fixed the issue but I'm just curious what caused the issue in the first place.  My local SDL2 install from HomeBrew is up to date.

**Comment by peppy** [comment]
I don't know how this interacts with local SDL installs sorry. The intended use case is to use the included binaries. I can confirm that `osx-x64` does work for us.

**Comment by elvodqa** [comment]
Thanks for the confirmation. I guess I need to change few things.
