### ISSUE TITLE
Add `SDL_GetWindowSizeInPixels` support?

### ISSUE THREAD

**Issue by KaKusaOAO** [ppy/SDL2-CS#181]
Hi, 

I was just looking at osu-framework source code and I found this: 
https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/SDL2/SDL2GraphicsSurface.cs#L80

This reminds me that I have tried to get drawable size for D3D11 and I found this: 
https://github.com/libsdl-org/SDL/issues/6105
https://wiki.libsdl.org/SDL2/SDL_GetWindowSizeInPixels

But that method does not exist in the wrapper, so I wonder if that method could be added?

**Comment by smoogipoo** [comment]
Please PR to upstream first, and we'll pull it into here.

**Comment by KaKusaOAO** [comment]
Hi,

I took a look and found that there was already a merged PR that adds `SDL_GetWindowSizeInPixels`.
https://github.com/flibitijibibo/SDL2-CS/pull/247

**Comment by peppy** [comment]
I've merged that in for the next release.

**Comment by peppy** [comment]
I've published a nuget release with this (https://www.nuget.org/packages/ppy.SDL2-CS/1.0.697-alpha).
