### ISSUE TITLE
Investigate switching build actions to use the same ones provided by SDL

### ISSUE THREAD

**Issue by peppy** [ppy/SDL2-CS#20]
SDL recently moved to github, and has build actions which are a lot simpler than the ones we use. May be worthwhile switching to them. Haven't done so yet because I'm not sure they 100% give the outputs we expect (they currently don't publish artifacts so it's hard to immediately tell).

https://github.com/libsdl-org/SDL/blob/main/.github/workflows/main.yml

**Comment by Thog** [comment]
I do have made something similar to that action to be able to have "nightly" every days [here](https://github.com/Thog/SDL-CI/blob/master/.github/workflows/ci.yml) if you want to check outputs.

I plan to work on bringing 32 bits support to it too (currently working on Apple Silicon compatibility)

**Comment by peppy** [comment]
Great stuff. I likely won't have time to look at this short-term myself, but I do plan on addressing a few more SDL-side issues we are facing, so it would be very helpful to alleviate the partially manual build process I am currently using.

One thing to note is that the macOS build process we are using doesn't support macOS 10.14 properly (see commit history for our attempts so far). Right now I'm building in a VM manually.

Feel free to contribute your solution if/when you see it fit for the task.

**Comment by Thog** [comment]
> 
> 
> Great stuff. I likely won't have time to look at this short-term myself, but I do plan on addressing a few more SDL-side issues we are facing, so it would be very helpful to alleviate the partially manual build process I am currently using.
> 
> One thing to note is that the macOS build process we are using doesn't support macOS 10.14 properly (see commit history for our attempts so far). Right now I'm building in a VM manually.
> 
> Feel free to contribute your solution if/when you see it fit for the task.

For the macOS 10.14 issue, is it caused by ABI incompatibilities on the objective C side or is it something else?

**Comment by peppy** [comment]
Yeah, I believe that's the case. Although even when setting the envvar it looked to crash with a different error so it needs further investigation.

Original issue: https://github.com/ppy/osu/issues/12244
Targeting 10.14 using latest xcode: https://github.com/ppy/SDL2-CS/blob/e230266ff3957e596b948c65ed983066aca871de/native/osx-x64/libSDL2.dylib (don't have the error log handy right now)

**Comment by Thog** [comment]
I just finished integrating 32 bits build and started diffing both libraries for the macOS issue.

The good library was built with sdk 14.0 (instead of 15.1) and it doesn't have a weak link to ``CoreHaptics.framework`` and ``GameController.framework``.

GameController framework was added in 10.9 but looking at CoreHaptics it seems to have appears in 2019 and isn't present on macOS 10.14.

This seems to be a mistake on SDL code where it check the max version supported instead of the min version [here](https://github.com/libsdl-org/SDL/blob/0bdf4f95bfc51de21ff6444ee1e1fdb7f6ad2661/src/joystick/iphoneos/SDL_mfijoystick.m#L87-L98).

As such a 10.14 sdk will not trigger the ``ENABLE_MFI_RUMBLE`` define and the code will end up not linking with CoreHaptics.

**Comment by peppy** [comment]
As it turns out, both your dylib and the one I linked work correctly. The issue I was running into was a signing/notarisation one. Safe to say the envvar targetting 10.14 *does* work correctly, which is good to know.

**Comment by Thog** [comment]
Reworked all CI with #22

**Comment by Xyene** [comment]
Just a heads up: as-is, the binaries produced on Linux post-#22 are incompatible with any system using a libc older than that provided in Ubuntu 20.04, which is a pretty new release.

The original setup built with Debian Jessie, which provided compatibility back to 2018 (notably, Ubuntu 18.04 is still a popular version). The original PR (https://github.com/ppy/SDL2-CS/pull/2) has more rationale for why the `libsdl-org/SDL` approach is not sufficient for broad compatibility.

If compatibility is in fact deemed a non-issue (alongside tying osu-framework's compatibility with whatever runners GitHub decides to ship -- eventually 20.04 will be removed in favor of something newer), then I'd suggest also removing https://github.com/ppy/SDL2-CS/tree/master/linux-build (it's dead code now).

**Comment by peppy** [comment]
Ah, we definitely want compatibility back to ubuntu 18, so best to leave things as they are for now. Thanks for the heads up.

**Comment by Thog** [comment]
> 
> 
> Ah, we definitely want compatibility back to ubuntu 18, so best to leave things as they are for now. Thanks for the heads up.

Oh yes, try switching the runner for linux to ``ubuntu-18.04`` I think it will works directly.

**Comment by Xyene** [comment]
I imagine it'd work with `ubuntu-16.04` as well (note this is still newer/less compatible than the Debian Jessie that was used previously), but fundamentally it feels a bit weird to tie the Linux versions SDL2-CS can run on to what runners GitHub Actions happens to provide today.

If today we switched the build environment to use `ubuntu-18.04` and tomorrow GitHub decided to sunset that runner, the minimum supported Linux version of all SDL2-CS consumers would increase overnight. It's a strange dependency to have. GitHub doesn't have an official deprecation policy, but given they have a nonzero maintenance cost, it's reasonable to expect they won't support 16/18.04 forever. Travis CI certainly does periodically remove runners.

**Comment by Thog** [comment]
> 
> 
> I imagine it'd work with `ubuntu-16.04` as well* (note this is still newer/less compatible than the Debian Jessie that was used previously), but fundamentally it feels a bit weird to tie the Linux versions SDL2-CS can run on to what runners GitHub Actions happens to provide today.
> 
> If today we switched the build environment to use `ubuntu-18.04` and tomorrow GitHub decided to sunset that runner, the minimum supported Linux version of all SDL2-CS consumers would increase overnight. It's a strange dependency to have. GitHub doesn't have an official deprecation policy, but given they have a nonzero maintenance cost, it's reasonable to expect they won't support 16/18.04 forever. Travis CI certainly does periodically remove runners.
> 
> * It might not have a new enough `wayland-protocols`, but they could be pinned from a newer release.

Other option could be just running it inside docker

**Comment by Xyene** [comment]
> Other option could be just running it inside docker

I agree, this is what the original CI setup was doing on Linux :)

https://github.com/ppy/SDL2-CS/pull/22/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L46-L57

I was under the impression that this was removed due to its relative complexity; I just wanted to bring up the downsides of doing so.

**Comment by peppy** [comment]
We can always switch back to a docker build if the time comes that we need to.

**Comment by peppy** [comment]
Closing this as mostly-addressed.
