### ISSUE TITLE
Disable DInput support on Windows

### ISSUE THREAD

**Issue by Thog** [ppy/SDL2-CS#44]
Hello there,

I have got multiple reports of the DInput COM object taking up to 1 min to init when you try to init the joystick or gamecontroller side on SDL2 on Ryujinx.

Would you be fine disabling it at build time?

**Comment by peppy** [comment]
Which devices would disabling affect? It sounds like it may reduce compatibility with a larger range of input devices. Is there any documentation related to this that can be used as a reference/

**Comment by Thog** [comment]
[DInput](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ee416842(v=vs.85)) is the legacy API that can handle joysticks.

Usage of it haven't been recommended for quite some time now (it also haven't got any update since DirectX 8)
The real issue I see here tho is that the replacement for it ([XInput](https://docs.microsoft.com/en-us/windows/win32/xinput/getting-started-with-xinput)) is designed for Xbox style controllers so I think raw joysticks with unconventional layouts still needs DInput.

On my side, for Ryujinx, I only use the game controller api so in the end I enforce a Xbox layout.

PS: If you want I can also just fork and have that one diff, I'm fine with it too ^^

**Comment by peppy** [comment]
Aware of what directinput is, but was more interested in a potential list of input devices which compatibility is lost for. I think it's safe to say we can't disable it for our purposes.

Out of curiosity, are you able to get some debug details from the users reporting freezes (memory dump / analyse stack trace during the freeze)? If it's not application specific, it sounds like something we are also going to run into sooner or later, so I'd like to know if it's something we can potentially fix upstream.

**Comment by VelocityRa** [comment]
@peppy Hey, I run into this about a week ago and debugged it a bit, here's a stacktrace screenshot i took.

![image](https://user-images.githubusercontent.com/6632271/116781229-539dee80-aa8a-11eb-9f37-fcb736802377.png)

It happens when it's initialized - patching out this call on SDl2.dll bypassed the issue.
https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/joystick/windows/SDL_dinputjoystick.c#L510-L511

**Comment by peppy** [comment]
That call doesn't look like anything special. Are you running any weird peripherals or OS versions which could potentially cause issue (anything non-standard)?

**Comment by VelocityRa** [comment]
Sorry should have specified, I didn't just patch out the call, I patched the code to `jmp` to the error path so it didn't run any of the other calls below it that actually do stuff. Presumable `IDirectInput8_Initialize` is the culprit.

**Comment by VelocityRa** [comment]
Running Windows 10. I have a DS3 controller plugged in & using ScpToolkit which _is_ known for being pretty dodgy. Nothing besides that, just regular k+m.

**Comment by VelocityRa** [comment]
We've had reports from another user (the only one I know besides me & Thog with the issue), who said disconnecting+reconnecting their mouse fixes the issue immediately instead of having to wait.

In my case, it's never properly fixed, I waited for 15 minutes. But the keyboard lag does go away after a while.

**Comment by peppy** [comment]
Sounds like this needs to be reported to SDL2 as a bug (on a quick search I couldn't find any reports, which means it's likely only affecting a *very* small percentage of users). Without actually seeing this being a widespread issue, it isn't something we would be jumping to disable on this fork anyway. I'd highly appreciate if you do this as it would both document the issue for future travellers and may even result in it getting fixed.

@Thog If you see these handful of reports as being enough reason to remove functionality from an upstream library for use case I think it's best you create a fork.

**Comment by VelocityRa** [comment]
Also wanted to mention: There is a GTK3-related issue with Ryujinx currently where on init it makes the keyboard input of the whole system lag for a bit. It's possible the issues are interconnected.

**Comment by peppy** [comment]
@VelocityRa if you're willing and want to help rule out whether it's something local to ryujinx or now, you could give lazer a try and see if you encounter the same issue on startup (https://github.com/ppy/osu#releases).

**Comment by smoogipoo** [comment]
In the interest of keeping code in one place, maybe it could be added as a hint and upstreamed from there? Seems like SDL already has a toggle for XInput: https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/include/SDL_hints.h#L466-L473 so I don't imagine it too complex to do the same for DInput.

I'm sure we've also encountered this in osu! - I remember some users having startup delays with certain keyboards plugged in. Not that we'd want to disable it necessarily (but maybe).

**Comment by peppy** [comment]
Yeah, again, we'd need to see which devices that people still use these days which rely on it being there. And whether the number of users using it is low enough that we can recommend they use a third party program to do the mapping to xinput (likely not).

**Comment by VelocityRa** [comment]
@peppy Good point - yeah lazer works fine for me, never had this issue.

**Comment by Thog** [comment]
> 
> 
> Sounds like this needs to be reported to SDL2 as a bug (on a quick search I couldn't find any reports, which means it's likely only affecting a _very_ small percentage of users). Without actually seeing this being a widespread issue, it isn't something we would be jumping to disable on this fork anyway. I'd highly appreciate if you do this as it would both document the issue for future travellers and may even result in it getting fixed.
> 
> @Thog If you see these handful of reports as being enough reason to remove functionality from an upstream library for use case I think it's best you create a fork.

Will fork for now, it's kind of hard to investigate this without having the issue itself in the first place.
We also have some plan to move away from GTK for the UI so I will come back to the regular dependency when that happen ^^

**Comment by Thog** [comment]
So in a weird turn of event one of my computer contracted the issue.
I confirmed that it's unrelated to GTK3 entirely via a simple test application.
It is taking 40s in ``IDirectInput8::EnumDevices`` [here](https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/joystick/windows/SDL_dinputjoystick.c#L695) and from a quick search around the web it suggests it could be caused by some bad dinput driver.

Will continue to investigate and report back if I find anything new.
